[package]
name = "tantivy_server"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "tantivy-server"
path = "src/main.rs"

[dependencies]
tantivy = "0.22"
tonic = "0.12"
prost = "0.13"
tokio = { version = "1", features = ["full"] }
anyhow = "1"
axum = "0.7"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
jieba-rs = "0.7"
lazy_static = "1.4"

[build-dependencies]
tonic-build = "0.12"
