<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>qknow-framework</artifactId>
        <groupId>tech.qiantong</groupId>
        <version>2.2.1</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>qknow-neo4j</artifactId>

    <description>
        qknow-neo4j框架核心
    </description>

    <dependencies>
        <dependency>
            <groupId>org.neo4j.driver</groupId>
            <artifactId>neo4j-java-driver</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-neo4j</artifactId>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-annotations</artifactId>
        </dependency>
        <dependency>
            <groupId>tech.qiantong</groupId>
            <artifactId>qknow-common</artifactId>
        </dependency>
    </dependencies>

</project>
