

neo4j:
  uri: bolt://127.0.0.1:7687
  user: neo4j
  password: InC3tmU4bijT4vkl
# neo4j日志
logging:
  level:
    org:
      neo4j:
#        driver: DEBUG
      springframework:
        data:
          neo4j: DEBUG
