

neo4j:
  uri: ${NEO4J_URI:bolt://127.0.0.1:7687}
  user: ${NEO4J_USER:neo4j}
  password: ${NEO4J_PASSWORD}
# neo4j日志
logging:
  level:
    org:
      neo4j:
#        driver: DEBUG
      springframework:
        data:
          neo4j: DEBUG
