# Copyright © 2026 Qiantong Technology Co., Ltd.
# qKnow Knowledge Platform
#  *
# License:
# Released under the Apache License, Version 2.0.
# You may use, modify, and distribute this software for commercial purposes
# under the terms of the License.
#  *
# Special Notice:
# All derivative versions are strictly prohibited from modifying or removing
# the default system logo and copyright information.
# For brand customization, please apply for brand customization authorization via official channels.
#  *
# More information: https://qknow.qiantong.tech/business.html
#  *
# ============================================================================
#  *
# 版权所有 © 2026 江苏千桐科技有限公司
# qKnow 知识平台（开源版）
#  *
# 许可协议：
# 本项目基于 Apache License 2.0 开源协议发布，
# 允许在遵守协议的前提下进行商用、修改和分发。
#  *
# 特别说明：
# 所有衍生版本不得修改或移除系统默认的 LOGO 和版权信息；
# 如需定制品牌，请通过官方渠道申请品牌定制授权。
#  *
# 更多信息请访问：https://qknow.qiantong.tech/business.html

version: "2.2.1"

services:
  redis:
    image: redis:6-alpine
    profiles: ["base"]
    env_file: .env
    restart: always
    environment:
      REDISCLI_AUTH: ${REDIS_PASSWORD:-tF0cC3aE2tD2hK0dA0oT}
#    volumes:
#      # Mount the redis data directory to the container.
#      - ./redis/data:/data
    # Set the redis password when startup redis server.
    command: redis-server --requirepass ${REDIS_PASSWORD:-tF0cC3aE2tD2hK0dA0oT}
    ports:
      - "${EXPOSE_REDIS_PORT:-6379}:6379"
    healthcheck:
      test: [ 'CMD', 'redis-cli', '-a', '${REDIS_PASSWORD}', 'ping' ]
    networks:
      - qknownet

  neo4j:
    image: neo4j:5.26.0
    profiles: ["base"]
    restart: always
    environment:
      - NEO4J_AUTH=neo4j/${NEO4J_PASSWORD:-aA3nJ7pF1iJ2cB0fM1nJ}
    ports:
      - "47474:7474"
      - "47687:7687"
    volumes:
      - ./database/neo4j/data:/data
      - ./database/neo4j/logs:/logs
    healthcheck:
      test: [ "CMD", "cypher-shell", "-u", "neo4j", "-p", "${NEO4J_PASSWORD:-aA3nJ7pF1iJ2cB0fM1nJ}", "RETURN 1;" ]
      interval: 30s      # 每 30 秒检查一次
      timeout: 10s       # 超过 10 秒算失败
      retries: 5         # 连续失败 5 次算 unhealthy
      start_period: 40s  # 容器启动后等待 40 秒再开始检测
    networks:
      - qknownet

  nginx:
    image: nginx:1.24.0
    restart: always
    profiles: ["base"]
    env_file: .env
    ports:
      - '${EXPOSE_NGINX_PORT:-80}:${NGINX_PORT:-80}'
    networks:
      - qknownet
    volumes:
      - ./nginx/dist:/usr/share/nginx
      - ./nginx/logs:/var/log/nginx
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/sites/:/etc/nginx/http_vhost/:ro

  #MySQL主库
  mysql57:
    image: mysql:5.7
    profiles: ["base"]
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD:  ${MYSQL_ROOT_PASSWORD}   # ← 修改成你的
      TZ: "Asia/Shanghai"                          # 如需改时区请改
    ports:
      - "23306:3306"
    volumes:
      - ./database/mysql/conf.d/my.cnf:/etc/mysql/conf.d/my.cnf:ro
      - ./database/mysql/init:/docker-entrypoint-initdb.d:ro
    networks:
      - qknownet
    healthcheck:
      test: [ "CMD-SHELL", "mysql -u root -p\"$MYSQL_ROOT_PASSWORD\" -e 'SELECT 1'" ]
      interval: 10s
      timeout: 10s
      retries: 15
      start_period: 60s
    extra_hosts:
      - "host.docker.internal:host-gateway"

  weaviate:
    image: semitechnologies/weaviate:1.32.23
    profiles: ["base"]
    restart: always
    ports:
      - "28080:8080"
      - "60051:50051"
    volumes:
      - ./database/weaviate:/var/lib/weaviate
    environment:
      PERSISTENCE_DATA_PATH: /var/lib/weaviate
      QUERY_DEFAULTS_LIMIT: 25
      CLUSTER_ENABLED: "false"
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: false
      DEFAULT_VECTORIZER_MODULE: none
      AUTHENTICATION_APIKEY_ENABLED: true
      AUTHENTICATION_APIKEY_ALLOWED_KEYS: WVF5YThaHlkYwhGUSmCRgsX3tD5ngdN8pkih
      AUTHENTICATION_APIKEY_USERS: hello@qknow
      AUTHORIZATION_ADMINLIST_ENABLED: true
      AUTHORIZATION_ADMINLIST_USERS: hello@qknow
    healthcheck:
      # 健康检查，确保服务正常启动
      test: [ "CMD", "curl", "-f", "http://localhost:8080/v1/meta" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - qknownet
