package tech.qiantong.qknow.module.kmc.service.rag;

import org.h2.jdbcx.JdbcDataSource;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.util.ReflectionTestUtils;
import tech.qiantong.qknow.module.kmc.api.knowledgeBase.dto.GraphRagResult;

import java.util.List;

import static org.junit.jupiter.api.Assertions.*;

class GraphRagRetrieverTest {

    private JdbcTemplate jdbcTemplate;
    private GraphRagProperties properties;
    private GraphRagRetriever retriever;

    @BeforeEach
    void setUp() {
        JdbcDataSource dataSource = new JdbcDataSource();
        dataSource.setURL("jdbc:h2:mem:graph_rag;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1");
        jdbcTemplate = new JdbcTemplate(dataSource);
        createSchema();

        properties = new GraphRagProperties();
        retriever = new GraphRagRetriever();
        ReflectionTestUtils.setField(retriever, "jdbcTemplate", jdbcTemplate);
        ReflectionTestUtils.setField(retriever, "properties", properties);
    }

    @Test
    void disabledGraphReturnsEmpty() {
        assertTrue(retriever.graphSearch(1L, List.of("A公司"), 10).isEmpty());
    }

    @Test
    void graphSearchReturnsEntityMatches() {
        properties.setEnabled(true);
        insertFixture();

        List<GraphRagResult> results = retriever.graphSearch(1L, List.of("A公司"), 10);

        assertEquals(1, results.size());
        assertEquals(100L, results.get(0).getSegmentId());
        assertTrue(results.get(0).getEvidence().contains("股东"));
    }

    @Test
    void emptyMigrationSucceeds() {
        GraphRagSyncService syncService = new GraphRagSyncService();
        ReflectionTestUtils.setField(syncService, "jdbcTemplate", jdbcTemplate);
        ReflectionTestUtils.setField(syncService, "properties", properties);

        assertEquals(0, syncService.migrateExistingMetadata());
    }

    @Test
    void cypherSafetyBlocksWrites() {
        CypherSafetyValidator validator = new CypherSafetyValidator();

        assertTrue(validator.isReadOnly("MATCH (n) RETURN n LIMIT 20"));
        assertFalse(validator.isReadOnly("MATCH (n) DELETE n RETURN n"));
        assertFalse(validator.isReadOnly("MATCH (n) RETURN n; MATCH (m) RETURN m"));
        assertFalse(validator.isReadOnly("MATCH (n) FOREACH (x IN [1] | SET n.v = x) RETURN n"));
        assertTrue(validator.isTemplateReadOnly("MATCH (n) UNWIND [1] AS x RETURN x"));
    }

    private void createSchema() {
        jdbcTemplate.execute("DROP ALL OBJECTS");
        jdbcTemplate.execute("""
                CREATE TABLE kmc_document (
                    id BIGINT PRIMARY KEY,
                    knowledge_base_id BIGINT,
                    name VARCHAR(255),
                    del_flag INTEGER DEFAULT 0
                )
                """);
        jdbcTemplate.execute("""
                CREATE TABLE kmc_document_segment (
                    id BIGINT PRIMARY KEY,
                    document_id BIGINT,
                    document_name VARCHAR(255),
                    content TEXT,
                    del_flag INTEGER DEFAULT 0
                )
                """);
        jdbcTemplate.execute("""
                CREATE TABLE kmc_segment_entity_metadata (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    document_id BIGINT,
                    segment_id BIGINT,
                    qm_segment_id VARCHAR(128),
                    entities TEXT,
                    relations TEXT
                )
                """);
    }

    private void insertFixture() {
        jdbcTemplate.update("INSERT INTO kmc_document(id, knowledge_base_id, name, del_flag) VALUES (10, 1, 'doc', 0)");
        jdbcTemplate.update("INSERT INTO kmc_document_segment(id, document_id, document_name, content, del_flag) VALUES (100, 10, 'doc', 'content', 0)");
        jdbcTemplate.update("""
                INSERT INTO kmc_segment_entity_metadata(document_id, segment_id, qm_segment_id, entities, relations)
                VALUES (10, 100, 'qm-1', '[\"A公司\"]', '[{\"source\":\"A公司\",\"relation\":\"股东\",\"target\":\"B公司\"}]')
                """);
    }
}
