<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>tech.qiantong</groupId>
        <artifactId>qKnow</artifactId>
        <version>2.2.1</version>
    </parent>

    <artifactId>qknow-mcp</artifactId>
    <packaging>pom</packaging>
    <description>模型上下文协议 (Model Context Protocol, MCP) 企业级原生子系统</description>

    <modules>
        <module>qknow-mcp-core</module>
        <module>qknow-mcp-server</module>
        <module>qknow-mcp-client</module>
    </modules>

</project>
